AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-course-patientcheckout

  Sample SAM Template for lambda-course-patientcheckout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-${AWS::Region}"
  PatientCheckoutLambda:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri corresponds to the subdirectory where the Java code lives within this project
      CodeUri: patientcheckout
      Handler: org.jimtough.aws.lambda.s3sns.PatientCheckoutLambda::handler
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-${AWS::Region}"
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
