AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-course-patientcheckout

  Sample SAM Template for lambda-course-patientcheckout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 20

Resources:
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-${AWS::Region}"
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutLambda:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri corresponds to the subdirectory where the Java code lives within this project
      CodeUri: patientcheckout
      Handler: org.jimtough.aws.lambda.s3sns.PatientCheckoutLambda::handler
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-${AWS::Region}"
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment:
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*

  BillManagementLambda:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri corresponds to the subdirectory where the Java code lives within this project
      CodeUri: patientcheckout
      Handler: org.jimtough.aws.lambda.s3sns.BillManagementLambda::handler
      Architectures:
        - x86_64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic
